name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Unit tests
        run: npm run test:ci

      - name: Install Playwright Browsers (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npx playwright install --with-deps

      - name: Install Playwright Browsers (macOS/Windows)
        if: matrix.os != 'ubuntu-latest'
        run: npx playwright install

      - name: E2E tests
        env:
          E2E_BASE_URL: http://localhost:3020
          NEXT_PUBLIC_FUTURISTIC_UI: 'true'
          NEXT_PUBLIC_E2E_HOOKS: 'true'
          PORT: '3020'
          TSC_COMPILE_ON_ERROR: 'true'
        run: npx playwright test || echo "Playwright tests failed; uploading report..." && exit 1

      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

